### ISSUE TITLE
flush call in parsePacket is slow

### ISSUE THREAD

**Issue by mtongnz** [sstaub/Ethernet3#16]
Using flush in the parsePacket is a slow way to skip unwanted data.  I've modified my fork with code to simply update the pointer on the w5500 so we don't have to transfer it over SPI.

I've only implemented it in the parsePacket function but I think it could work or be better to simply rewrite the flush function with my changes.

I'd like to know if there's a reason for reading rather than skipping unwanted data using flush?

[https://github.com/mtongnz/Ethernet3](https://github.com/mtongnz/Ethernet3)

**Comment by sstaub** [comment]
no answer, so it will closed
