### ISSUE TITLE
In wol mode, w5500 can't wake up after sending a magic packet

### ISSUE THREAD

**Issue by lanzhihao** [sstaub/Ethernet3#17]
with this library, I use  
###### set IMR and MR register
 digitalWrite(10, LOW);
  //  send in the address and value via SPI:
  SPI.transfer((IMR & 0x00FF0000)>>16);
  SPI.transfer((IMR & 0x0000FF00)>> 8);
  SPI.transfer((IMR & 0x000000F8) + 4);
  SPI.transfer(0x10);
  // take the SS pin high to de-select the chip:
  digitalWrite(10, HIGH); 

  Ethernet.WoL(true);
######
 after that , I send magic packet but w5500 doesn't wake up and INT is still high

**Comment by sstaub** [comment]
I don't know what you do before calling Ethernet.WoL(true),
but I think you must call the function before Ethernet.begin()

**Comment by lanzhihao** [comment]
It is ok to realize that functionality. By the way But why I can't find the realization of the way in w5500 class, such as writeMR, it shows no definition in vs-code 
void W5500Class::swReset() {
  writeMR( (readMR() | 0x80) );
}
