### ISSUE TITLE
Problem with lardge TCP data.

### ISSUE THREAD

**Issue by Stanleyvc** [sstaub/Ethernet3#21]
With Arduino made a Audio system (Teensy with the SGTL5000 codex)  and the audio files can upload and download from pc to the teensy with a WIZ5500 ethernet board.

Form Teensy to PC is good.

From PC to Teensy is wrong, when de TCP buffer fulll, the data is not paused?

Thanks.

**Comment by sstaub** [comment]
Maybe you ask this question in the teensy or arduino forum. There are no changes for tcp, it is based on the original ethernet2 library.
