### ISSUE TITLE
Not a Issue but need help.

### ISSUE THREAD

**Issue by josephchrzempiec** [sstaub/Ethernet3#25]
Hello i don't have a issue really. I'm trying to figure out how to keep the wiznet 550io module power down. I don't need to run it at a full 100 mb connection using your Library. Can you help me out please?

**Comment by sstaub** [comment]
To power down the PHY use Ethernet.phyMode(POWER_DOWN), like described in the Readme. I never really test it.

**Comment by josephchrzempiec** [comment]
hello i don't want to power down the Wiznet it's self. the module it's self does take a lot of power. Is it possible to draw less current Because I'm not transferring speeds at 100M at a time?

**Comment by sstaub** [comment]
There is no sleep mode or anything else to reduce power consumption. You can try to use 10Mb mode.
