### ISSUE TITLE
Udp Multicast

### ISSUE THREAD

**Issue by Stanleyvc** [sstaub/Ethernet3#27]
Hai,

With Ethernet3 is it possible te sent and receive Multicast messages? 

How can I do? 

Thanks.

**Comment by sstaub** [comment]
EthernetUdp udp
upd.beginMulticast(multicastIP, port);
it is also described at the readme and the official Arduino API documentation.

**Comment by Stanleyvc** [comment]
Yes i see.

**I Declare the Multicast IP and the port for  setup()**:
IPAddress MIP(239,100,100,100);
uint8_t MPORT = 8910;
EthernetUDP mc;

**Into setup:**
mc.beginMulticast(MIP, MPORT);

**I have a multicast send routine:**
void multicast_send(String text) {
    mc.beginPacket(MIP, MPORT);
    char bu[text.length() + 1];
    text.toCharArray(bu,text.length() + 1);
    mc.write(bu,text.length() + 1);
    Serial.println(bu);
    mc.endPacket();
}

Nothing send to multicast.

Is there a example?

Thanks.****

**Comment by sstaub** [comment]
port must a 16bit variable, uint16_t MPORT = 8910;

**Comment by Stanleyvc** [comment]
Thanks.
