### ISSUE TITLE
Using the alternate SPI on stm32/blue pill

### ISSUE THREAD

**Issue by chechu2k5** [sstaub/Ethernet3#28]
I am presently looking to use a W5500 board with a stm32f103 based "Bluepill" development board. 

![w5500](https://user-images.githubusercontent.com/5258640/64500991-73a8ea80-d274-11e9-9ab3-d8cd0a9149d4.png)

![bluepill](https://user-images.githubusercontent.com/5258640/64500958-49efc380-d274-11e9-9abd-0dceaac57e37.png)

While I am successfully able to use this library on the default SPI pins, I'd like to be able to use the second SPI bus available on this microcontroller. 

* From what I can tell the SPIClass instance "SPI" is effectively hard coded as the first SPI (exposed on pins PA4/PA5/PA6/PA7). 
* The second SPI I am interested in using is available on pins PB12/PB13/PB14/PB15 as can been seen in the second image above.
* Cursory reading of W5500.h/cpp indicates the use of the default SPI instance everywhere.
Is there existing way or any plan to support the selection of a particular SPI instance within this library ?

Thanks

P.S. I couldn't find a way attach a "question label" to this issue ..

**Comment by sstaub** [comment]
You have to do some changes in W5500.h 
When you look to https://github.com/stm32duino/Arduino_Core_STM32/tree/master/libraries/SPI
there is a possibility to use a constructor for using different SPIs. I think you have to call
SPIClass::SPIClass(uint8_t mosi, uint8_t miso, uint8_t sclk, uint8_t ssel)
ssel must be a hardware CS pin
It is not planned to support different SPIs ports.

**Comment by chechu2k5** [comment]
Thank you for your quick response. 
I will investigate further based on your suggestion.
