### ISSUE TITLE
ICMP ping library not compatible

### ISSUE THREAD

**Issue by BorgMcz** [sstaub/Ethernet3#30]
Hello, I have encountered a problem with the library compatibility https://github.com/BlakeFoster/Arduino-Ping. Don't know another usable library of the same features, compatible with yours? Or you could not modify the icmp_ping library for use. My knowledge is not enough for this adjustment :-(

Thank you.

**Comment by sstaub** [comment]
Sorry, in the moment I have not the time to make this library compatible. To advices:
Ethernet.h must changed to Ethernet3.h
In the code I see many access to the w5100.h, in Ethernet3 lib this is w5500.h so you need to change the access methods form w5100.xxxxxx to w550.xxxxxx
Hope this helps.

**Comment by BorgMcz** [comment]
I found the library functional:

https://github.com/NicksonYap/Arduino-Ping-W5500/ 
(in ICMPPing.h needs to be changed ethernet3.h)
