### ISSUE TITLE
Does not work with Nano (old bootloader) & Wiz5500io combo

### ISSUE THREAD

**Issue by baqwas** [sstaub/Ethernet3#32]
Sorry for posting this issue but the last update to the Wiznet library is several years older. The following code snippet fails to return a lease from the DHCP server:

```
#include <Ethernet3.h>
#include <EthernetUdp3.h>
uint8_t MACaddress[6];
...
  if (Ethernet.begin(MACaddress) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // no point in carrying on, so do nothing forevermore:
    for (;;)
      ;
  }
```
The target machine is a Nano and the ETH shield is WIZ5500io. Thanks.

Kind regards.

**Comment by sstaub** [comment]
The WIZ550IO needs no mac address, try without.

**Comment by baqwas** [comment]
Understood. Closing issue owing to stupidity on my part. I burnt UNO bootloader to the Schenzen Nano (which had ATmega328P Old Bootloader). Thx all the same for your quick response and guidance.

Kind regards.
