### ISSUE TITLE
I have designed a esp board with W5500 but no reset/int pin connected,does this matter?

### ISSUE THREAD

**Issue by CxZMoE** [sstaub/Ethernet3#33]
Here is my schemetic:
![1605797620](https://user-images.githubusercontent.com/39299424/99682435-27814900-2aba-11eb-8bea-4f87d714b40a.png)

and I set PMOD registers as 1,1,1 (leave unconnected and  pull-up internally)
![1605797820(1)](https://user-images.githubusercontent.com/39299424/99682744-8fd02a80-2aba-11eb-9168-b87a489ae5b9.jpg)
is that ok? I really hope someone can help me out. Thanks.

**Comment by sstaub** [comment]
Missing interupt pin is no problem, for reset there is a software Bades reset function.

**Comment by CxZMoE** [comment]
> Missing interupt pin is no problem, for reset there is a software based reset function.

OHHHH thank you,you helped me a lot!!!

**Comment by CxZMoE** [comment]
Does ETHERNET3 compatible with the Arduino MQTT library? I see there is a EthernetClient class.

**Comment by sstaub** [comment]
It seems the MQTT library is only for WIFI vonnection.

**Comment by CxZMoE** [comment]
> It seems the MQTT library is only for WIFI vonnection.

We use this statement to initialize a MQTT client,the `net` is a WiFiClient which inherited from Client,
```
client.begin("39.108.90.170", 1883, net);
```
and then I saw your code file "EthernetClient.cpp",there is an EthernetClient which is also inherited from Client and implemented the functions declared in the parent Client class.
Maybe this will work??

**Comment by CxZMoE** [comment]
> It seems the MQTT library is only for WIFI vonnection.

We use this statement to initialize a MQTT client,the `net` is a WiFiClient which inherited from Client,
```
client.begin("ip", 1883, net);
```
and then I saw your code file "EthernetClient.cpp",there is an EthernetClient which is also inherited from Client and implemented the functions declared in the parent Client class.
Maybe this will work??

**Comment by sstaub** [comment]
I think this should work, but you need different names for the class members.

**Comment by CxZMoE** [comment]
> I think this should work, but you need different names for the class members.

Yes,your library works amazingly well on my self-designed esp-w5500 board!! Thanks a lot!!!

**Comment by sstaub** [comment]
Fine
