### ISSUE TITLE
Nit: Ethernet::setHostname could take a const char*

### ISSUE THREAD

**Issue by jamessynge** [sstaub/Ethernet3#38]
There doesn't seem to be a reason for the string to be non-const, so that would simplify things for the caller.

**Comment by sstaub** [comment]
You mean changing
`void setHostname(char* hostname);`
to
`void setHostname(const char* hostname);`

**Comment by sstaub** [comment]
Done!

**Comment by jamessynge** [comment]
Thanks very much.
