### ISSUE TITLE
Unable to create the server

### ISSUE THREAD

**Issue by biswaKL** [sstaub/Ethernet3#41]
In ESP32, I have added W5500
Want to use both Wifi and LAN

While Compiling I am getting this Error.

```cannot declare variable 'server' to be of abstract type 'EthernetServer'```

**Comment by biswaKL** [comment]
I Modified the server library a bit. and now looks fine

```
#ifndef ethernetserver_h
#define ethernetserver_h

#include "Server.h"

class EthernetClient;

class EthernetServer : public Server
{
private:
  uint16_t _port;
  void accept();

public:
  // EthernetServer(uint16_t port);
  EthernetClient available();
  void begin(uint16_t port = 0);
  size_t write(uint8_t);
  size_t write(const uint8_t *buf, size_t size);
  using Print::write;
};

#endif

```

**Comment by sstaub** [comment]
How did you use the variable server? which context? is the variable also a class name? Did you tried another variable name?
