### ISSUE TITLE
EthernetServer::available() won't connect unless remote end SENDS something

### ISSUE THREAD

**Issue by mlord** [sstaub/Ethernet3#42]
This bug has been around forever.  EthernetServer::available() is used to get a new inbound connection on a socket.  But it won't actually return the new connection unless/until the remote end SENDs data to the socket.  This causes trouble for several situations, including stuff I have ported from Ethernet and EthernetENC libraries.

Simple fix:  get rid of the incorrect check of client.available() in there, which currently causes the connection attempt to be ignored unless data is available() from the remote end.

**Comment by sstaub** [comment]
can you make a PR?

**Comment by mlord** [comment]
Sorry, no.  I'm not a git person.

**Comment by mlord** [comment]
I'll see about some sample code for testing -- it's all currently part of a much larger codebase.  But here is the simple patch I am using to correct it.

Thanks for responding!

[Ethernet2_connect_fix.patch.txt](https://github.com/sstaub/Ethernet3/files/6445973/Ethernet2_connect_fix.patch.txt)

**Comment by mlord** [comment]
Here is a test program for seeing the bug, and verifying the fix.  This one has enough verbose output to show when a connection is established, and when it disconnects again.

Load the sketch onto any Arduino with a W5500 connected, and open the serial monitor (115200).  Then "telnet -8 xx.xx.xx.xx 23" to connect to it without sending data.  The sketch will not display any output.  Then hit enter in the telnet session, and the sketch will only then say "connected".

Repeat the test with the fix applied, and now one should see "connected" immediately upon establishment of the telnet session.

[testEthernet2.ino.txt](https://github.com/sstaub/Ethernet3/files/6446138/testEthernet2.ino.txt)

**Comment by sstaub** [comment]
You use the Ethernet2 library, not the Ethernet3.

**Comment by mlord** [comment]
Same bug, exact same line of code.  I'll pull down Ethernet3 and recheck it.

**Comment by mlord** [comment]
Re-tested, re-verified, exact same bug, exact same place, exact same fix.
Thanks.

**Comment by mlord** [comment]
So.. closed but no intent to apply the fix, or what?

**Comment by vjmuzik** [comment]
If this is supposed to somewhat follow the official API then there should be two separate functions. Server.available() waits for data and Server.accept() doesn’t.

**Comment by sstaub** [comment]
The examples and fixes use the Ethernet2 library not the Ethernet3. If it persists make a PR.

**Comment by mlord** [comment]
As already noted above, the examples and fixes apply equally to both Ethernet3 and Ethernet2.  Problem still persists.
