### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SvizelPritula** [sstaub/Ethernet3#52]
Hello,
I can't help but notice that the repository contains no license file and that the source code file contain no license header. This would mean that the library is completely proprietary and that it's therefore illegal to use this library with the Arduino framework. Is this on purpose?

**Comment by sstaub** [comment]
Most parts are based on the Ethernet2 library were most licenses are missing because there are no infos about most parts of it. This makes library not illegal.

**Comment by SvizelPritula** [comment]
Huh, you are right about that. Some of the files in Ethernet2 contain a license header while some don't, which is weird.

However, I'm afraid this just means both libraries are legally unusable with the Arduino framework.
