### ISSUE TITLE
Wiz550io Help! 

### ISSUE THREAD

**Issue by EdBeardon** [sstaub/Ethernet3#55]
Hi, I'm trying to run a basic piece of code to pick up the MAC address stored on my Wiz550io. I've had a look at the help files but can't find an example to start with. I've got this working on the Ethernet2 library but I need it working on Ethernet3. The code pick up the IP address fine but MAC is shown as 00:00:00:00:00:00. See code below: 

`#include <SPI.h>
#include <Ethernet3.h>
#define WIZ550io_WITH_MACADDRESS

int8_t isConnected = 0;
uint8_t mac[6]; // array for mac address
void macAddress(uint8_t mac[]); // get the MAC Address
const char* macAddressReport();

IPAddress ip(192, 168, 0, 50);

void setup() {

  Serial.begin(9600);
  Ethernet.begin(mac, ip);;
  Serial.println("Write something here");
  
}

void loop() {

  Serial.println(ip);

  delay(1000);
}`

**Comment by sstaub** [comment]
- `#include <SPI.h>` is not needed
- `void macAddress(uint8_t mac[]); // get the MAC Address` must done in setup() because it is a function, `void` is not necessary. It is only needed when you need the MAC address for other purpose but should not necessary.
- same for `const char* macAddressReport();` it is complete wrong, try `Serial.println(macAddressReport());`
- `Ethernet.begin(mac, ip);;` should replaced by `Ethernet.begin(ip);`

**Comment by EdBeardon** [comment]
Hi, thank you. Can you confirm the following should now work?

`#include <Ethernet3.h>
#define WIZ550io_WITH_MACADDRESS


int8_t isConnected = 0;
uint8_t mac[6]; // array for mac address

IPAddress ip(192, 168, 0, 50);

void setup() {

  macAddress(uint8_t mac[]); // get the MAC Address
  Serial.begin(9600);
  Ethernet.begin(ip);;
  Serial.println("Write something here");
  
}

void loop() {

  Serial.println(ip);
  Serial.println(macAddressReport());
  delay(1000);
}`

**Comment by sstaub** [comment]
It should work, maybe macAddress will work after Ethernet.begin(ip)

**Comment by EdBeardon** [comment]
Hi again, see below:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/93470919/213915281-e319e4c4-9298-4df8-b699-fe1ff922bd71.png">

**Comment by sstaub** [comment]
Use `macAddress(mac[]); // get the MAC Address`
This are basics of c programming

**Comment by EdBeardon** [comment]
Thanks for your help so far, unfortunately its still not compiling.  I was hoping I could find an example to base my code from. Thanks again!
<img width="581" alt="image" src="https://user-images.githubusercontent.com/93470919/213931119-00ec049a-5c38-4008-abb5-aef9bef3c862.png">

**Comment by sstaub** [comment]
Sorry try `macAddress(mac); // get the MAC Address`

**Comment by EdBeardon** [comment]
All compiles okay now. I would assume both macAdress & macAddressReport need to be defined? 

I've uploaded to my board with no luck, I've tried with 2 different WIZ550ios. 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/93470919/213932692-9e2012d6-853d-4bbe-bca0-e57373f88865.png">

**Comment by sstaub** [comment]
Sorry, I don't understand what you do. Please learn the basics of C before doing wrong things.

**Comment by EdBeardon** [comment]
Hi, can you confirm if this should work?

`#include <Ethernet3.h>
#define macAddressReport
#define macAddress
#define WIZ550io_WITH_MACADDRESS

//SETUP FOR IP
IPAddress ip(192, 168, 0, 50);
IPAddress subnet(255, 255, 255, 0);
IPAddress gateway(192, 168, 0, 1);

//TO STORE MAC ADDRESS IN
uint8_t mac[6];

void setup() {
  
Serial.begin(115200);
   
macAddress(mac); // get the MAC Address

Ethernet.begin(mac, ip, gateway, subnet);

for (int i = 0; i < 6; i++) {
if (mac[i] < 16) {
Serial.print("0");
}
Serial.print(mac[i], HEX);
if (i < 5) {
Serial.print(":");
}
}
Serial.println(macAddressReport);
Serial.println();
Serial.println(Ethernet.localIP());
}

void loop() {
  


}`

**Comment by sstaub** [comment]
The short answer NO
